
skillMetadata:
  sections:
    - name: CalDAV Server Credentials
      fields:
        - type: label
          label: Enter your CalDAV server credentials for the user you wish to connect to, default placeholder settings are used here
        - name: username
          type: text
          label: Username
          value: "test1"
        - name: password
          type: password
          label: Password
          value: ""
        - name: url
          type: text
          label: url for CalDAV server
          value: ""
